# Generated by Django 5.0.6 on 2025-09-04 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('orientador', models.CharField(blank=True, max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='produtividade.group')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('turma', models.CharField(max_length=50)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='produtividade.group')),
            ],
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pontualidade', models.PositiveSmallIntegerField(default=0)),
                ('comunicacao', models.PositiveSmallIntegerField(default=0)),
                ('qualidade_codigo', models.PositiveSmallIntegerField(default=0)),
                ('entrega_tarefas', models.PositiveSmallIntegerField(default=0)),
                ('resolucao_problemas', models.PositiveSmallIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='produtividade.group')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='produtividade.project')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='produtividade.student')),
            ],
            options={
                'unique_together': {('data', 'aluno', 'projeto')},
            },
        ),
    ]
