# Generated by Django 5.1.2 on 2025-09-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['grupo', 'data'], name='produtivida_grupo_i_e17e15_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['grupo', 'aluno', 'data'], name='produtivida_grupo_i_808f48_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['grupo', 'projeto', 'data'], name='produtivida_grupo_i_867e09_idx'),
        ),
    ]
